// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghmzvpwwcmijjwimhlew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdobXp2cHd3Y21pamp3aW1obGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjE2NzAsImV4cCI6MjA2NzE5NzY3MH0.Uzb0xm2c4cCExUXfQM-sW9QAgHDaMYPTGm8iRiUZUHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});